on: [push, pull_request_target]

jobs:
  test_get_owners_action:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Parse OWNERS
        id: owners
        uses: imlunahey/owners-check@468467407620733b2614cbf980e649987f2098bf
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
