on: [pull_request_target]

permissions: write-all

jobs:
  test_get_owners_action:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Owners check
        id: owners
        uses: imlunahey/owners-check@a7d1b47443cf9d3674be113c4bd6822c3c648d3a
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
